baseURL = 'https://baszy.github.io'
languageCode = 'en-us'
title = 'Basile S.'
theme = 'villainy'
pluralizelisttitles = false
enableEmoji = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'algol'
    tabWidth = 8

[menu]
  [[menu.nav]]
    Name = "Home"
    URL = "/"
    weight = 1
  [[menu.nav]]
    Name = "Posts"
    URL = "/posts/"
    weight = 2
  [[menu.nav]]
    Name = "Software"
    URL = "/software/"
    weight = 3
  [[menu.nav]]
    Name = "Contact"
    URL = "/contact/"
    weight = 4
